const chatWindow = document.getElementById("chat-window");

// Offline Knowledge Base (~150+ questions can be expanded)
const healthFAQ = {
  // Greetings
  "hi": "🤖 MITHRA: Hello! How can I help you today?",
  "hello": "🤖 MITHRA: Hi there! Ask me any health-related question.",
  "hey": "🤖 MITHRA: Hey! I’m MITHRA, your health assistant.",
  "how are you": "🤖 MITHRA: I’m an AI chatbot, always ready to assist you!",
  "good morning": "🤖 MITHRA: Good morning! How can I help you today?",
  "good evening": "🤖 MITHRA: Good evening! Do you have any health queries?",
  "thanks": "🤖 MITHRA: You’re welcome!",
  "thank you": "🤖 MITHRA: Happy to help!",
  "bye": "🤖 MITHRA: Goodbye! Stay healthy!",
  "good night": "🤖 MITHRA: Good night! Take care of your health.",

  // General Health
  "what is health": "🤖 MITHRA: Health is a state of complete physical, mental, and social well-being.",
  "why is health important": "🤖 MITHRA: Health is important because it allows us to live productively and happily.",
  "how to stay healthy": "🤖 MITHRA: Eat balanced food, exercise daily, sleep well, and manage stress.",
  "how to improve health": "🤖 MITHRA: Small changes like good diet, regular workouts, and avoiding smoking help a lot.",
  "tips for healthy life": "🤖 MITHRA: Eat fruits, drink water, avoid junk food, and sleep at least 7-9 hours daily.",

  // Common Illnesses
  "fever": "🤖 MITHRA: Fever is a rise in body temperature. Drink fluids, rest, and consult a doctor if it persists.",
  "cold": "🤖 MITHRA: For a common cold, rest well, drink fluids, and take vitamin C.",
  "flu": "🤖 MITHRA: Flu symptoms include fever, cough, sore throat, fatigue, and body aches.",
  "headache": "🤖 MITHRA: Headaches can be caused by stress, dehydration, or lack of sleep.",
  "migraine": "🤖 MITHRA: Migraines are severe headaches. Rest in a dark room and consult a doctor if frequent.",
  "stomach ache": "🤖 MITHRA: Stomach ache can be due to indigestion, gas, or infection. Stay hydrated and eat light food.",
  "diarrhea": "🤖 MITHRA: Drink plenty of fluids, avoid junk food, and consult a doctor if severe.",
  "constipation": "🤖 MITHRA: Eat high-fiber foods, drink water, and exercise regularly.",
  "vomiting": "🤖 MITHRA: Vomiting can be caused by infection or food issues. Stay hydrated and rest.",
  "cough": "🤖 MITHRA: A cough may result from allergies, cold, or infections. Drink warm fluids and consult if prolonged.",
  "sore throat": "🤖 MITHRA: Gargle with warm salt water, drink warm fluids, and rest your voice.",

  // Chronic Conditions
  "diabetes": "🤖 MITHRA: Diabetes affects blood sugar. Eat healthy and exercise regularly.",
  "blood sugar": "🤖 MITHRA: Maintain normal blood sugar with diet, exercise, and medicines if prescribed.",
  "blood pressure": "🤖 MITHRA: Normal blood pressure is around 120/80 mmHg.",
  "hypertension": "🤖 MITHRA: Hypertension is high blood pressure. Reduce salt, exercise, and monitor regularly.",
  "heart disease": "🤖 MITHRA: Eat healthy, exercise, avoid smoking, and monitor cholesterol levels.",
  "obesity": "🤖 MITHRA: Maintain healthy weight with balanced diet and regular exercise.",
  "cholesterol": "🤖 MITHRA: Keep cholesterol in check by avoiding fatty foods and exercising regularly.",
  "asthma": "🤖 MITHRA: Asthma affects breathing. Avoid triggers and carry inhalers if prescribed.",
  "arthritis": "🤖 MITHRA: Arthritis causes joint pain. Exercise lightly, eat anti-inflammatory foods, and consult a doctor.",
  "thyroid": "🤖 MITHRA: Thyroid imbalance affects energy and weight. Regular checkups and medicines help.",
  "cancer": "🤖 MITHRA: Early detection improves treatment outcomes. Avoid smoking and maintain healthy lifestyle.",

  // Preventive Health
  "exercise": "🤖 MITHRA: Regular exercise improves physical and mental health.",
  "healthy diet": "🤖 MITHRA: Eat fruits, vegetables, whole grains, lean proteins, and avoid excessive sugar.",
  "hydration": "🤖 MITHRA: Drink at least 8 glasses of water daily for proper hydration.",
  "sleep": "🤖 MITHRA: Aim for 7-9 hours of quality sleep every day.",
  "stress": "🤖 MITHRA: Practice mindfulness, meditation, and deep breathing to reduce stress.",
  "mental health": "🤖 MITHRA: Take breaks, socialize, and consult a professional if needed.",
  "vaccination": "🤖 MITHRA: Vaccines protect against many diseases. Follow the vaccination schedule.",
  "hygiene": "🤖 MITHRA: Wash hands frequently, cover your mouth when sneezing, and maintain personal hygiene.",
  "sun safety": "🤖 MITHRA: Protect skin by using sunscreen and avoiding too much sun exposure.",
  "first aid": "🤖 MITHRA: Keep a basic first aid kit with bandages, antiseptic, and pain relief.",

  // Women’s Health
  "menstruation": "🤖 MITHRA: Maintain hygiene during periods, and consult a doctor if pain is severe.",
  "pregnancy": "🤖 MITHRA: Eat nutritious food, stay hydrated, and consult your doctor regularly.",
  "breast health": "🤖 MITHRA: Regular self-checks and mammograms help early detection of breast issues.",
  "pcos": "🤖 MITHRA: PCOS affects hormones. Balanced diet, exercise, and doctor guidance help manage it.",
  "menopause": "🤖 MITHRA: Menopause is a natural phase. Lifestyle changes and support help ease symptoms.",

  // Men’s Health
  "prostate health": "🤖 MITHRA: Regular checkups and healthy lifestyle help maintain prostate health.",
  "sexual health": "🤖 MITHRA: Practice safe sex, get tested, and consult a doctor for concerns.",
  "fertility": "🤖 MITHRA: Healthy diet, stress reduction, and lifestyle habits improve fertility.",

  // Children & Elderly
  "child health": "🤖 MITHRA: Ensure balanced diet, vaccinations, and regular exercise for children.",
  "elderly health": "🤖 MITHRA: Focus on diet, exercise, regular checkups, and mental well-being for seniors.",
  "immunity": "🤖 MITHRA: Eat healthy, exercise, sleep well, and avoid stress to boost immunity.",
  "nutrition": "🤖 MITHRA: Include proteins, vitamins, and minerals in your diet for overall health.",
  "growth": "🤖 MITHRA: Children need protein, calcium, and vitamins for proper growth.",

  // Emergencies
  "chest pain": "🤖 MITHRA: Chest pain can be serious. Call emergency services immediately.",
  "shortness of breath": "🤖 MITHRA: Seek medical attention immediately if severe.",
  "injury": "🤖 MITHRA: Clean the wound, apply antiseptic, and consult a doctor if needed.",
  "poisoning": "🤖 MITHRA: Call emergency services and follow poison control instructions.",
  "burn": "🤖 MITHRA: Run cool water over burn, cover lightly, and seek medical care if severe.",
  "fracture": "🤖 MITHRA: Immobilize the area and seek immediate medical help.",

  // COVID
  "covid": "🤖 MITHRA: COVID-19 is caused by coronavirus. Wash hands, wear masks, and maintain distance.",
  "covid symptoms": "🤖 MITHRA: Symptoms include fever, cough, fatigue, and loss of taste or smell.",
  "covid prevention": "🤖 MITHRA: Vaccination, masks, handwashing, and distancing prevent spread.",
  "covid recovery": "🤖 MITHRA: Rest, hydration, and follow doctor’s advice after COVID infection.",
  "long covid": "🤖 MITHRA: Some may face fatigue and breathing issues post-COVID. Consult doctor.",

  // Lifestyle & Daily
  "why exercise": "🤖 MITHRA: Exercise improves fitness, mental health, and prevents chronic diseases.",
  "why eat healthy": "🤖 MITHRA: Healthy eating provides essential nutrients and reduces disease risk.",
  "how to reduce stress": "🤖 MITHRA: Practice meditation, deep breathing, and regular exercise.",
  "how to lose weight": "🤖 MITHRA: Combine balanced diet, regular exercise, and sufficient sleep.",
  "how to gain weight": "🤖 MITHRA: Eat protein-rich foods, healthy fats, and perform strength training.",
  "what is immunity": "🤖 MITHRA: Immunity is the body’s ability to fight infections and stay healthy.",
  "how to improve immunity": "🤖 MITHRA: Eat nutritious food, sleep well, exercise, and manage stress.",
  "what is mental health": "🤖 MITHRA: Mental health includes emotional, psychological, and social well-being.",
  "how to improve mental health": "🤖 MITHRA: Practice mindfulness, social interaction, and seek help when needed.",

    // Nutrition & Diet
  "what is nutrition": "🤖 MITHRA: Nutrition is the process of providing the body with necessary food for health and growth.",
  "why is nutrition important": "🤖 MITHRA: Good nutrition helps prevent disease, supports growth, and boosts immunity.",
  "what is a balanced diet": "🤖 MITHRA: A balanced diet includes fruits, vegetables, whole grains, protein, and healthy fats.",
  "best diet for weight loss": "🤖 MITHRA: A diet rich in vegetables, lean protein, and low in processed foods helps weight loss.",
  "best diet for weight gain": "🤖 MITHRA: Include nuts, seeds, dairy, eggs, and healthy fats along with strength training.",
  "best diet for diabetes": "🤖 MITHRA: Whole grains, vegetables, lean proteins, and limited sugars help control diabetes.",
  "foods for strong bones": "🤖 MITHRA: Calcium-rich foods like milk, yogurt, and leafy greens strengthen bones.",
  "foods for brain health": "🤖 MITHRA: Omega-3 fish, nuts, berries, and green vegetables support brain function.",
  "foods for heart health": "🤖 MITHRA: Oats, nuts, olive oil, fish, and fruits improve heart health.",
  "foods for skin glow": "🤖 MITHRA: Hydration, fruits, vitamin C, and antioxidants help skin stay healthy.",
  "foods for hair growth": "🤖 MITHRA: Protein, iron, and vitamins from eggs, spinach, and nuts support hair growth.",
  "foods rich in vitamin c": "🤖 MITHRA: Citrus fruits, guava, bell peppers, and strawberries are rich in vitamin C.",
  "foods rich in vitamin d": "🤖 MITHRA: Sunlight, fortified milk, and fish provide vitamin D.",
  "foods rich in iron": "🤖 MITHRA: Spinach, lentils, red meat, and beans are good iron sources.",
  "foods rich in protein": "🤖 MITHRA: Eggs, chicken, fish, tofu, lentils, and beans provide protein.",
  "foods rich in calcium": "🤖 MITHRA: Dairy, almonds, and leafy greens are calcium-rich.",
  "foods rich in fiber": "🤖 MITHRA: Whole grains, fruits, vegetables, and legumes provide fiber.",
  "foods rich in antioxidants": "🤖 MITHRA: Blueberries, green tea, and dark chocolate are antioxidant-rich.",

  // Exercise & Fitness
  "what is exercise": "🤖 MITHRA: Exercise is physical activity that improves fitness and health.",
  "why is exercise important": "🤖 MITHRA: Exercise strengthens muscles, heart, and improves mood.",
  "types of exercise": "🤖 MITHRA: Cardio, strength training, flexibility, and balance exercises.",
  "best exercise for weight loss": "🤖 MITHRA: Running, cycling, swimming, and HIIT are effective for weight loss.",
  "best exercise for weight gain": "🤖 MITHRA: Strength training builds muscle mass along with proper diet.",
  "best exercise for heart health": "🤖 MITHRA: Brisk walking, swimming, and cycling improve heart health.",
  "exercise for kids": "🤖 MITHRA: Outdoor play, running, and sports keep kids healthy.",
  "exercise for seniors": "🤖 MITHRA: Walking, yoga, and light strength training are good for elderly health.",
  "yoga benefits": "🤖 MITHRA: Yoga improves flexibility, reduces stress, and boosts immunity.",
  "meditation benefits": "🤖 MITHRA: Meditation reduces stress, improves focus, and supports mental health.",
  "walking benefits": "🤖 MITHRA: Walking improves heart health, burns calories, and reduces stress.",
  "running benefits": "🤖 MITHRA: Running builds stamina, burns fat, and strengthens heart and lungs.",
  "cycling benefits": "🤖 MITHRA: Cycling improves fitness, reduces stress, and supports joint health.",
  "swimming benefits": "🤖 MITHRA: Swimming builds endurance, strengthens muscles, and improves lung capacity.",
  "strength training benefits": "🤖 MITHRA: It builds muscles, boosts metabolism, and supports bone strength.",
  "stretching benefits": "🤖 MITHRA: Stretching improves flexibility, posture, and reduces injury risk.",
  "how much exercise per day": "🤖 MITHRA: Adults should aim for at least 30 minutes of moderate exercise daily.",

  // Sleep & Rest
  "why is sleep important": "🤖 MITHRA: Sleep restores energy, repairs the body, and supports brain function.",
  "how many hours of sleep": "🤖 MITHRA: Adults need 7–9 hours, teens 8–10 hours, children 9–12 hours.",
  "what is insomnia": "🤖 MITHRA: Insomnia is difficulty falling or staying asleep.",
  "causes of insomnia": "🤖 MITHRA: Stress, caffeine, irregular schedule, or medical conditions can cause insomnia.",
  "how to sleep better": "🤖 MITHRA: Maintain routine, avoid screens, and relax before bedtime.",
  "what is sleep apnea": "🤖 MITHRA: A disorder where breathing repeatedly stops during sleep. Needs medical care.",
  "what are dreams": "🤖 MITHRA: Dreams are thoughts, images, or sensations during sleep.",
  "why do we dream": "🤖 MITHRA: Dreams help process emotions and memories, though science is still studying them.",
  "importance of naps": "🤖 MITHRA: Short naps improve alertness and memory.",
  "best sleeping position": "🤖 MITHRA: Sleeping on your back or side supports the spine.",

  // Mental Health
  "what is stress": "🤖 MITHRA: Stress is the body’s reaction to pressure or challenges.",
  "how to reduce stress": "🤖 MITHRA: Meditation, deep breathing, and exercise reduce stress.",
  "what is anxiety": "🤖 MITHRA: Anxiety is excessive worry or fear about everyday situations.",
  "how to reduce anxiety": "🤖 MITHRA: Breathing exercises, therapy, and relaxation help reduce anxiety.",
  "what is depression": "🤖 MITHRA: Depression is a mood disorder causing sadness and loss of interest.",
  "signs of depression": "🤖 MITHRA: Sadness, fatigue, sleep problems, and loss of interest in activities.",
  "how to treat depression": "🤖 MITHRA: Therapy, medication, exercise, and support can help.",
  "what is mindfulness": "🤖 MITHRA: Mindfulness is being fully present in the moment without judgment.",
  "benefits of mindfulness": "🤖 MITHRA: It reduces stress, improves focus, and supports emotional well-being.",
  "what is therapy": "🤖 MITHRA: Therapy is professional support for mental health and emotional challenges.",
  "what is counseling": "🤖 MITHRA: Counseling is guidance provided by professionals to resolve personal issues.",
  "importance of mental health": "🤖 MITHRA: Good mental health improves relationships, productivity, and happiness.",
  "what is burnout": "🤖 MITHRA: Burnout is physical and mental exhaustion caused by stress and overwork.",
  "how to recover from burnout": "🤖 MITHRA: Rest, set boundaries, and seek support from others.",

  // First Aid Basics
  "first aid for burns": "🤖 MITHRA: Cool burn under water, cover lightly, and seek care if severe.",
  "first aid for cuts": "🤖 MITHRA: Clean with water, apply antiseptic, and cover with a bandage.",
  "first aid for nosebleed": "🤖 MITHRA: Sit upright, lean forward, and pinch nose until bleeding stops.",
  "first aid for fainting": "🤖 MITHRA: Lay person down, elevate legs, and loosen tight clothing.",
  "first aid for choking": "🤖 MITHRA: Perform Heimlich maneuver or back blows if person cannot breathe.",
  "first aid for insect bite": "🤖 MITHRA: Wash area, apply ice, and use anti-itch cream.",
  "first aid for snake bite": "🤖 MITHRA: Keep person still, avoid movement, and seek immediate medical care.",
  "first aid for fracture": "🤖 MITHRA: Immobilize area and get medical help quickly.",
  "first aid for heart attack": "🤖 MITHRA: Call emergency, keep person calm, and give aspirin if advised.",
  "first aid for stroke": "🤖 MITHRA: Act FAST – Face drooping, Arm weakness, Speech issues, Time to call emergency.",

  // Hygiene
  "importance of hygiene": "🤖 MITHRA: Hygiene prevents diseases and keeps the body clean.",
  "types of hygiene": "🤖 MITHRA: Personal hygiene, food hygiene, and environmental hygiene.",
  "hand washing importance": "🤖 MITHRA: Washing hands prevents infections and disease spread.",
  "oral hygiene tips": "🤖 MITHRA: Brush twice daily, floss, and visit dentist regularly.",
  "bath importance": "🤖 MITHRA: Regular bathing removes germs and refreshes the body.",
  "nail hygiene": "🤖 MITHRA: Trim and clean nails to avoid bacterial infections.",
  "hair hygiene": "🤖 MITHRA: Wash regularly and keep scalp clean to prevent dandruff and lice.",

  // Vaccination
  "what is vaccination": "🤖 MITHRA: Vaccination protects against infectious diseases by building immunity.",
  "importance of vaccination": "🤖 MITHRA: Vaccines save lives by preventing serious illnesses.",
  "child vaccination": "🤖 MITHRA: Children should follow routine immunization schedule.",
  "adult vaccination": "🤖 MITHRA: Adults may need vaccines for flu, tetanus, and travel-related diseases.",
  "flu vaccine": "🤖 MITHRA: Annual flu shots reduce risk of influenza.",
  "covid vaccine": "🤖 MITHRA: COVID-19 vaccines reduce severity and spread of infection.",
  "hepatitis vaccine": "🤖 MITHRA: Protects against liver infection caused by hepatitis virus.",
  "hpv vaccine": "🤖 MITHRA: Protects against human papillomavirus that can cause cancer."

 
  "what is stress": "Stress is the body's response to pressure or challenging situations.",
  "symptoms of stress|signs of stress": "Headache, fatigue, irritability, poor sleep, difficulty concentrating.",
  "how to reduce stress|ways to manage stress": "Practice relaxation, deep breathing, meditation, yoga, exercise, and proper rest.",
  "what is anxiety": "Anxiety is excessive worry or fear that interferes with daily life.",
  "symptoms of anxiety|signs of anxiety": "Restlessness, rapid heartbeat, sweating, difficulty concentrating, irritability.",
  "how to manage anxiety": "Relaxation techniques, mindfulness, talking to a friend, therapy, and healthy routines.",
  "what is depression": "Depression is a mental health condition with persistent sadness, loss of interest, and low energy.",
  "symptoms of depression": "Feeling sad, hopelessness, lack of energy, poor sleep, loss of appetite, loss of interest.",
  "how to treat depression": "Therapy, lifestyle changes, medication (if prescribed), and strong social support.",
  "importance of sleep": "Good sleep restores the body, boosts immunity, and supports mental health.",
  "how many hours of sleep are needed": "Adults need 7–9 hours, teens need 8–10 hours, children need more depending on age.",
  "what causes insomnia": "Stress, caffeine, irregular routines, depression, or certain medications.",
  "how to improve sleep|tips for better sleep": "Maintain a routine, avoid screens before bed, limit caffeine, and keep the room dark and cool.",
  "what is obesity": "Obesity is excessive body fat that increases the risk of diabetes, heart disease, and hypertension.",
  "causes of obesity": "Overeating, sedentary lifestyle, genetics, and hormonal imbalances.",
  "how to prevent obesity": "Balanced diet, regular exercise, portion control, and avoiding junk food.",
  "what is diabetes": "Diabetes is a condition where blood sugar levels are too high due to insulin problems.",
  "symptoms of diabetes": "Frequent urination, thirst, fatigue, slow healing wounds, blurry vision.",
  "how to manage diabetes": "Healthy eating, regular activity, monitoring sugar, and taking medicines if prescribed.",
  "what is hypertension|what is high blood pressure": "Hypertension is when blood pressure remains consistently above normal.",
  "symptoms of high blood pressure": "Often none; sometimes headaches, dizziness, or nosebleeds.",
  "how to prevent hypertension": "Reduce salt, exercise, maintain weight, avoid smoking and alcohol.",
  "what is heart attack": "A heart attack occurs when blood flow to the heart is blocked.",
  "symptoms of heart attack": "Chest pain, shortness of breath, sweating, pain in arms/jaw/back.",
  "first aid for heart attack": "Call emergency services, keep the person calm, give aspirin if available.",
  "what is stroke": "A stroke happens when blood supply to part of the brain is interrupted.",
  "symptoms of stroke": "Face drooping, arm weakness, speech difficulty (FAST test).",
  "first aid for stroke": "Call emergency immediately, keep patient safe and calm.",
  "what is asthma": "Asthma is a condition where airways narrow, making breathing difficult.",
  "symptoms of asthma": "Wheezing, shortness of breath, chest tightness, coughing at night.",
  "treatment of asthma": "Inhalers, avoiding triggers, and following medical advice.",
  "what is allergy": "An allergy is an immune system reaction to a substance like dust, pollen, or food.",
  "symptoms of allergy": "Sneezing, itching, runny nose, skin rash, swelling.",
  "treatment for allergy": "Avoid allergens, take antihistamines, or use prescribed medicines.",
  "what is migraine": "Migraine is a severe headache often with nausea, vomiting, or light sensitivity.",
  "symptoms of migraine": "Throbbing headache, vision problems, nausea, sensitivity to sound/light.",
  "treatment for migraine": "Rest in a dark room, hydration, pain relief medicines, avoid triggers.",
  "importance of exercise": "Exercise improves heart health, strengthens muscles, and boosts mood.",
  "how much exercise is needed daily": "At least 30 minutes of moderate activity most days of the week.",
  "what is yoga": "Yoga combines physical postures, breathing, and meditation for health and relaxation.",
  "benefits of yoga": "Improves flexibility, reduces stress, strengthens the body, and calms the mind.",
  "what is meditation": "Meditation is the practice of focusing the mind to achieve relaxation and awareness.",
  "benefits of meditation": "Reduces stress, improves focus, supports emotional health.",
  "what is CPR": "CPR (Cardiopulmonary Resuscitation) is an emergency technique to keep blood and oxygen flowing when heart stops.",
  "steps of CPR": "Check response, call emergency, give chest compressions, rescue breaths if trained.",
  "what is choking": "Choking happens when an object blocks the airway.",
  "first aid for choking": "Encourage coughing, give abdominal thrusts (Heimlich maneuver) if needed.",
  "what is dehydration": "Dehydration is when the body loses more fluids than it takes in.",
  "symptoms of dehydration": "Thirst, dry mouth, dizziness, dark urine, fatigue.",
  "how to prevent dehydration": "Drink enough water daily, especially in hot weather or during exercise.",
  "what is nutrition": "Nutrition is the process of consuming food for growth, energy, and health.",
  "importance of balanced diet": "Provides energy, supports immunity, and prevents disease.",
  "what are proteins": "Proteins are body-building nutrients found in eggs, fish, beans, and meat.",
  "what are carbohydrates": "Carbs provide energy; sources include rice, bread, fruits, and vegetables.",
  "what are fats": "Fats store energy and protect organs; healthy fats are in nuts, fish, and olive oil.",
  "what are vitamins": "Vitamins are essential nutrients that help the body function properly.",
  "what are minerals": "Minerals like calcium, iron, and zinc support bones, blood, and immunity.",
  "importance of water": "Water is vital for hydration, digestion, temperature regulation, and health."
 // Part 4: Health FAQ (901–1200)
const healthFAQ_part4 = {
  "what is cancer": "Cancer is uncontrolled growth of abnormal cells in the body.",
  "symptoms of cancer": "Unexplained weight loss, fatigue, lumps, persistent cough, abnormal bleeding.",
  "prevention of cancer": "Avoid smoking, eat healthy, exercise, and get regular screenings.",
  "what is tuberculosis": "Tuberculosis (TB) is an infectious disease affecting the lungs.",
  "symptoms of tuberculosis": "Persistent cough, chest pain, weight loss, night sweats, fever.",
  "treatment of tuberculosis": "Long-term antibiotics as prescribed by a doctor.",
  "what is malaria": "Malaria is a mosquito-borne disease caused by parasites.",
  "symptoms of malaria": "Fever, chills, sweating, headache, nausea.",
  "prevention of malaria": "Use mosquito nets, repellents, and eliminate stagnant water.",
  "what is dengue": "Dengue is a viral disease spread by Aedes mosquitoes.",
  "symptoms of dengue": "High fever, severe headache, joint pain, skin rash.",
  "treatment of dengue": "No specific medicine, supportive care, hydration, and rest.",
  "what is hepatitis": "Hepatitis is liver inflammation caused by viruses or toxins.",
  "types of hepatitis": "Hepatitis A, B, C, D, and E differ in causes and severity.",
  "symptoms of hepatitis": "Jaundice, fatigue, abdominal pain, dark urine.",
  "prevention of hepatitis": "Vaccination, safe food/water, and safe practices.",
  "what is anemia": "Anemia is a lack of healthy red blood cells to carry oxygen.",
  "symptoms of anemia": "Fatigue, pale skin, weakness, dizziness, shortness of breath.",
  "treatment of anemia": "Iron-rich foods, supplements, or medical treatment.",
  "what is osteoporosis": "Osteoporosis weakens bones, making them fragile.",
  "prevention of osteoporosis": "Calcium, vitamin D, exercise, and avoiding smoking/alcohol.",
  "what is arthritis": "Arthritis is inflammation of joints causing pain and stiffness.",
  "types of arthritis": "Osteoarthritis and rheumatoid arthritis are common types.",
  "treatment of arthritis": "Exercise, medicines, physical therapy, and joint care.",
  "what is alzheimer": "Alzheimer’s disease is a progressive brain disorder causing memory loss.",
  "symptoms of alzheimer": "Memory decline, confusion, difficulty speaking and understanding.",
  "how to prevent alzheimer": "Healthy lifestyle, brain exercises, social activity, balanced diet.",
  "what is parkinson": "Parkinson’s disease affects movement due to low dopamine levels.",
  "symptoms of parkinson": "Tremors, stiffness, slow movement, balance issues.",
  "treatment of parkinson": "Medicines, therapy, and supportive care.",
  "what is epilepsy": "Epilepsy is a brain condition causing seizures.",
  "symptoms of epilepsy": "Uncontrolled movements, loss of consciousness, staring spells.",
  "first aid for seizure": "Do not restrain, keep safe, turn on side, call emergency if prolonged.",
  "what is hiv": "HIV is a virus that weakens the immune system.",
  "how is hiv transmitted": "Unprotected sex, shared needles, mother-to-child, blood transfusion.",
  "prevention of hiv": "Safe sex, clean needles, and regular testing.",
  "what is aids": "AIDS is the advanced stage of HIV infection with severe immune damage.",
  "symptoms of aids": "Frequent infections, weight loss, night sweats, fatigue.",
  "treatment of hiv aids": "Antiretroviral therapy (ART) controls the virus and prolongs life.",
  "what is kidney stone": "Kidney stones are hard deposits in the kidneys.",
  "symptoms of kidney stone": "Severe pain, blood in urine, nausea, frequent urination.",
  "prevention of kidney stone": "Drink water, reduce salt, avoid excess protein.",
  "what is liver cirrhosis": "Cirrhosis is severe liver damage from alcohol, hepatitis, or fatty liver.",
  "symptoms of liver cirrhosis": "Jaundice, swelling, fatigue, confusion.",
  "treatment of cirrhosis": "Lifestyle changes, medicines, or liver transplant in severe cases.",
  "what is pneumonia": "Pneumonia is a lung infection caused by bacteria, viruses, or fungi.",
  "symptoms of pneumonia": "Cough with phlegm, fever, chills, chest pain, difficulty breathing.",
  "treatment of pneumonia": "Antibiotics (if bacterial), rest, hydration, and medical care.",
  "what is bronchitis": "Bronchitis is inflammation of bronchial tubes in the lungs.",
  "symptoms of bronchitis": "Cough with mucus, fatigue, shortness of breath, chest discomfort.",
  "treatment of bronchitis": "Rest, fluids, medicines if needed.",
  "what is influenza": "Influenza (flu) is a viral infection affecting the respiratory system.",
  "symptoms of influenza": "Fever, cough, sore throat, muscle pain, fatigue.",
  "prevention of influenza": "Vaccination, hygiene, avoiding close contact with sick people.",
  "what is covid 19": "COVID-19 is a viral respiratory disease caused by coronavirus.",
  "symptoms of covid 19": "Fever, cough, fatigue, loss of taste/smell, breathing difficulty.",
  "prevention of covid 19": "Masking, vaccination, hand hygiene, and social distancing.",
  "what is monkeypox": "Monkeypox is a viral disease with symptoms like fever and rash.",
  "symptoms of monkeypox": "Fever, headache, muscle pain, rash with blisters.",
  "prevention of monkeypox": "Avoid close contact with infected persons, maintain hygiene.",
  "what is cholera": "Cholera is a bacterial infection causing severe diarrhea and dehydration.",
  "symptoms of cholera": "Watery diarrhea, vomiting, dehydration, rapid heartbeat.",
  "prevention of cholera": "Clean water, hygiene, and proper sanitation.",
  "what is typhoid": "Typhoid is a bacterial infection from contaminated food/water.",
  "symptoms of typhoid": "High fever, abdominal pain, weakness, rash, constipation/diarrhea.",
  "treatment of typhoid": "Antibiotics, fluids, and rest.",
  "what is rabies": "Rabies is a viral disease transmitted through animal bites.",
  "symptoms of rabies": "Fever, headache, fear of water, confusion, paralysis.",
  "prevention of rabies": "Immediate vaccination after bite, avoid stray animals.",
  "what is tetanus": "Tetanus is a bacterial infection causing muscle stiffness.",
  "symptoms of tetanus": "Jaw stiffness, muscle spasms, difficulty swallowing.",
  "prevention of tetanus": "Vaccination and proper wound care.",
  "what is polio": "Polio is a viral disease that can cause paralysis.",
  "symptoms of polio": "Fever, fatigue, headache, muscle weakness, paralysis in severe cases.",
  "prevention of polio": "Polio vaccination.",
  "what is measles": "Measles is a highly contagious viral disease.",
  "symptoms of measles": "Fever, cough, runny nose, red eyes, rash.",
  "prevention of measles": "MMR vaccination.",
  "what is mumps": "Mumps is a viral infection affecting salivary glands.",
  "symptoms of mumps": "Swelling of cheeks/jaw, fever, headache.",
  "prevention of mumps": "MMR vaccination.",
  "what is chickenpox": "Chickenpox is a viral infection causing itchy blisters.",
  "symptoms of chickenpox": "Fever, rash with blisters, fatigue.",
  "prevention of chickenpox": "Vaccination and avoiding contact with infected people.",
  "what is shingles": "Shingles is a painful rash caused by reactivation of chickenpox virus.",
  "symptoms of shingles": "Painful rash, blisters, burning sensation.",
  "treatment of shingles": "Antiviral medicines, pain relief, and proper care.",
  "what is cataract": "Cataract is clouding of the eye’s lens causing blurred vision.",
  "symptoms of cataract": "Blurred vision, glare, faded colors, difficulty at night.",
  "treatment of cataract": "Surgery to replace lens with artificial one.",
  "what is glaucoma": "Glaucoma is eye disease damaging the optic nerve.",
  "symptoms of glaucoma": "Vision loss, eye pain, halos around lights.",
  "treatment of glaucoma": "Eye drops, medicines, or surgery to lower eye pressure.",
  "what is conjunctivitis": "Conjunctivitis (pink eye) is eye inflammation caused by infection or allergy.",
  "symptoms of conjunctivitis": "Red eyes, itching, discharge, watery eyes.",
  "treatment of conjunctivitis": "Eye drops, hygiene, avoid touching eyes.",
  "what is ear infection": "Ear infection is inflammation in the middle or outer ear.",
  "symptoms of ear infection": "Ear pain, fever, hearing problems, fluid discharge.",
  "treatment of ear infection": "Antibiotics (if bacterial), pain relief, and rest.",
  "what is sinusitis": "Sinusitis is inflammation of the sinuses.",
  "symptoms of sinusitis": "Headache, nasal congestion, facial pain, thick mucus.",
  "treatment of sinusitis": "Steam inhalation, medicines, saline sprays.",
  "what is tonsillitis": "Tonsillitis is inflammation of the tonsils.",
  "symptoms of tonsillitis": "Sore throat, swollen tonsils, fever, difficulty swallowing.",
  "treatment of tonsillitis": "Rest, fluids, pain relievers, antibiotics if bacterial.",
  "what is appendicitis": "Appendicitis is inflammation of the appendix requiring surgery.",
  "symptoms of appendicitis": "Severe abdominal pain (right side), fever, nausea, vomiting.",
  "treatment of appendicitis": "Surgical removal of the appendix.",
  "what is gastritis": "Gastritis is inflammation of the stomach lining.",
  "symptoms of gastritis": "Stomach pain, nausea, bloating, loss of appetite.",
  "treatment of gastritis": "Medicines, diet changes, avoid alcohol and spicy food."
  // Part 5: Health FAQ (1201–1500)
const healthFAQ_part5 = {
  "what is dehydration": "Dehydration happens when the body loses more fluids than it takes in.",
  "symptoms of dehydration": "Thirst, dry mouth, dizziness, dark urine, fatigue.",
  "prevention of dehydration": "Drink plenty of fluids, especially in hot weather or during exercise.",
  "what is heat stroke": "Heat stroke is a life-threatening condition caused by overheating.",
  "symptoms of heat stroke": "High body temperature, confusion, rapid pulse, unconsciousness.",
  "first aid for heat stroke": "Move to a cool place, cool the body with wet cloths, seek emergency help.",
  "what is hypothermia": "Hypothermia is dangerously low body temperature.",
  "symptoms of hypothermia": "Shivering, confusion, slurred speech, loss of coordination.",
  "first aid for hypothermia": "Warm the person gradually, remove wet clothing, give warm drinks if conscious.",
  "what is anemia in children": "Anemia in children is low hemoglobin levels causing fatigue and weakness.",
  "causes of childhood anemia": "Poor diet, iron deficiency, infections, genetic conditions.",
  "treatment of childhood anemia": "Iron supplements, balanced diet, medical care.",
  "what is obesity in children": "Childhood obesity is excessive fat accumulation affecting health.",
  "prevention of childhood obesity": "Healthy diet, physical activity, limiting screen time.",
  "what is autism": "Autism spectrum disorder affects communication and behavior.",
  "symptoms of autism": "Difficulty with social interaction, repetitive behaviors, delayed speech.",
  "support for autism": "Therapies, special education, supportive environment.",
  "what is adhd": "ADHD is Attention Deficit Hyperactivity Disorder.",
  "symptoms of adhd": "Inattention, hyperactivity, impulsiveness.",
  "treatment of adhd": "Therapies, medications, behavioral strategies.",
  "what is depression": "Depression is a mental health disorder causing persistent sadness.",
  "symptoms of depression": "Hopelessness, fatigue, loss of interest, sleep changes.",
  "treatment of depression": "Therapy, medications, lifestyle support.",
  "what is anxiety": "Anxiety is excessive worry or fear.",
  "symptoms of anxiety": "Restlessness, rapid heartbeat, sweating, nervousness.",
  "treatment of anxiety": "Therapy, breathing exercises, medications if needed.",
  "what is bipolar disorder": "Bipolar disorder causes mood swings from depression to mania.",
  "symptoms of bipolar disorder": "Extreme highs (mania) and lows (depression).",
  "treatment of bipolar disorder": "Mood stabilizers, therapy, lifestyle management.",
  "what is schizophrenia": "Schizophrenia is a severe mental disorder affecting thoughts and behavior.",
  "symptoms of schizophrenia": "Hallucinations, delusions, disorganized speech, social withdrawal.",
  "treatment of schizophrenia": "Antipsychotics, therapy, supportive care.",
  "what is stroke": "Stroke occurs when blood supply to the brain is interrupted.",
  "symptoms of stroke": "Sudden numbness, trouble speaking, vision problems, weakness.",
  "first aid for stroke": "Call emergency immediately, note time of symptoms.",
  "what is heart attack": "Heart attack happens when blood flow to the heart is blocked.",
  "symptoms of heart attack": "Chest pain, sweating, nausea, pain in arm/jaw.",
  "first aid for heart attack": "Call emergency, keep patient calm, give aspirin if available.",
  "what is cpr": "CPR is Cardiopulmonary Resuscitation, a lifesaving procedure.",
  "how to perform cpr": "Push hard and fast in the center of the chest, 100–120 compressions per minute.",
  "what is hypertension crisis": "Hypertensive crisis is extremely high blood pressure needing emergency care.",
  "symptoms of hypertension crisis": "Severe headache, chest pain, vision problems, confusion.",
  "what is low blood pressure": "Low blood pressure (hypotension) is abnormally low circulation pressure.",
  "symptoms of low blood pressure": "Dizziness, fainting, blurred vision, fatigue.",
  "what is obesity management": "Obesity management includes diet, exercise, behavior therapy, and sometimes surgery.",
  "what is metabolic syndrome": "Metabolic syndrome is a cluster of conditions increasing heart disease risk.",
  "conditions of metabolic syndrome": "High blood sugar, high blood pressure, high cholesterol, excess fat.",
  "prevention of metabolic syndrome": "Healthy diet, weight control, exercise.",
  "what is gout": "Gout is arthritis caused by uric acid buildup.",
  "symptoms of gout": "Joint pain, redness, swelling, especially in the big toe.",
  "treatment of gout": "Medicines, avoiding purine-rich foods, hydration.",
  "what is thyroid disease": "Thyroid disease affects metabolism due to hormone imbalance.",
  "hypothyroidism": "Low thyroid hormone causing fatigue, weight gain, dry skin.",
  "hyperthyroidism": "Excess thyroid hormone causing weight loss, anxiety, rapid heartbeat.",
  "treatment of thyroid disease": "Medicines, hormone therapy, or surgery.",
  "what is pcos": "Polycystic Ovary Syndrome is a hormonal disorder in women.",
  "symptoms of pcos": "Irregular periods, weight gain, acne, excess hair growth.",
  "treatment of pcos": "Lifestyle changes, medications, and hormone therapy.",
  "what is infertility": "Infertility is inability to conceive after one year of trying.",
  "causes of infertility": "Ovulation issues, low sperm count, blocked tubes, age factors.",
  "treatment of infertility": "Medications, surgery, IVF or assisted reproductive techniques.",
  "what is menopause": "Menopause is the natural end of menstrual cycles in women.",
  "symptoms of menopause": "Hot flashes, mood swings, irregular periods, night sweats.",
  "treatment of menopause symptoms": "Hormone therapy, lifestyle adjustments.",
  "what is prostate cancer": "Prostate cancer is a cancer in the male prostate gland.",
  "symptoms of prostate cancer": "Urination difficulty, blood in urine, pelvic discomfort.",
  "screening for prostate cancer": "PSA blood test and medical checkups.",
  "what is breast cancer": "Breast cancer starts in breast tissue.",
  "symptoms of breast cancer": "Lump, skin changes, nipple discharge.",
  "prevention of breast cancer": "Self-exams, mammograms, healthy lifestyle.",
  "what is cervical cancer": "Cervical cancer occurs in the cervix due to HPV infection.",
  "prevention of cervical cancer": "HPV vaccination, regular screening.",
  "what is anemia in pregnancy": "Anemia in pregnancy is low hemoglobin levels needing iron supplements.",
  "what is gestational diabetes": "Gestational diabetes is diabetes developing during pregnancy.",
  "management of gestational diabetes": "Healthy diet, exercise, blood sugar monitoring.",
  "what is postpartum depression": "Postpartum depression is sadness and anxiety after childbirth.",
  "treatment of postpartum depression": "Therapy, support, and sometimes medication.",
  "what is asthma": "Asthma is a lung condition with inflamed airways.",
  "symptoms of asthma": "Coughing, wheezing, chest tightness, shortness of breath.",
  "treatment of asthma": "Inhalers, medicines, avoiding triggers.",
  "what is copd": "COPD is Chronic Obstructive Pulmonary Disease causing breathing problems.",
  "symptoms of copd": "Cough with mucus, shortness of breath, fatigue.",
  "treatment of copd": "Medicines, oxygen therapy, lifestyle changes.",
  "what is sleep apnea": "Sleep apnea is interrupted breathing during sleep.",
  "symptoms of sleep apnea": "Loud snoring, daytime sleepiness, choking in sleep.",
  "treatment of sleep apnea": "CPAP machine, weight loss, surgery in severe cases.",
  "what is insomnia": "Insomnia is difficulty falling or staying asleep.",
  "treatment of insomnia": "Sleep hygiene, relaxation, therapy, sometimes medication.",
  "what is migraine": "Migraine is a severe headache with nausea, light/sound sensitivity.",
  "treatment of migraine": "Rest, medicines, avoiding triggers.",
  "what is addiction": "Addiction is compulsive dependence on substances or behaviors.",
  "types of addiction": "Alcohol, drugs, smoking, gambling, internet.",
  "treatment of addiction": "Therapy, rehab programs, support groups.",
  "what is vaccination": "Vaccination provides immunity against diseases.",
  "benefits of vaccination": "Prevents disease, saves lives, reduces outbreaks.",
  "common vaccines": "MMR, polio, hepatitis, flu, covid.",
  "what is first aid": "First aid is immediate help given before medical care.",
  "first aid kit items": "Bandages, antiseptic, gloves, scissors, pain relievers.",
  "what is balanced diet": "Balanced diet provides nutrients in correct amounts.",
  "food groups in balanced diet": "Carbohydrates, proteins, fats, vitamins, minerals, water.",
  "benefits of exercise": "Exercise improves heart health, weight, mood, and strength.",
  "what is meditation": "Meditation is a practice of focus and relaxation for mental health.",
  "benefits of meditation": "Reduces stress, improves concentration, enhances well-being.",
  "what is yoga": "Yoga is a physical and mental practice combining postures and breathing.",
  "benefits of yoga": "Improves flexibility, reduces stress, enhances health.",
  "what is hygiene": "Hygiene is keeping oneself clean to prevent illness.",
  "types of hygiene": "Personal, food, environmental, oral.",
  "oral hygiene tips": "Brush twice daily, floss, regular dental checkups.",
  "what is immunity": "Immunity is the body’s defense against infections.",
  "how to boost immunity": "Eat healthy, sleep well, exercise, avoid stress.",
  "what is nutrition": "Nutrition is the process of providing or obtaining food for health.",
  "macronutrients": "Carbohydrates, proteins, fats.",
  "micronutrients": "Vitamins and minerals needed in small amounts.",
  "what is mental health": "Mental health is emotional, psychological, and social well-being.",
  "how to maintain mental health": "Positive lifestyle, stress control, social connections, therapy if needed.",
  "what is reproductive health": "Reproductive health ensures safe and responsible reproduction.",
  "family planning methods": "Contraceptives, safe sex practices, health education.",
  "what is hygiene in children": "Hand washing, oral care, bathing, nail trimming.",
  "elderly care tips": "Balanced diet, exercise, medical checkups, mental support.",
  "common childhood diseases": "Measles, mumps, chickenpox, diarrhea, cough, asthma.",
  "what is first aid for burns": "Cool with water, cover with clean cloth, avoid breaking blisters.",
  "what is fracture": "Fracture is a broken bone.",
  "first aid for fracture": "Immobilize, support with splint, seek medical help.",
  "what is poisoning": "Poisoning is harmful effect of substances swallowed, inhaled, or touched.",
  "first aid for poisoning": "Call emergency, do not induce vomiting unless told.",
  "what is wound care": "Clean, disinfect, cover, and monitor wounds for infection.",
  "what is skin health": "Skin health involves protecting from infections and maintaining hygiene.",
  "tips for healthy skin": "Hydrate, sunscreen, balanced diet, avoid smoking.",
  "what is eye care": "Eye care prevents vision problems.",
  "eye care tips": "Regular checkups, limit screen time, good lighting.",
  "what is hearing care": "Protect ears from loud noise, clean ears safely, regular checkups.",
  "importance of regular checkups": "Helps detect diseases early and prevent complications."
  const healthFAQ = {
  // 1501–1800: Expanded Health Topics

  // Dental & Oral Health
  "toothache": "🤖 MITHRA: For toothache, rinse your mouth with warm salt water and consult a dentist if pain persists.",
  "cavity": "🤖 MITHRA: Cavities are caused by tooth decay. Brush, floss, and visit your dentist regularly.",
  "gum bleeding": "🤖 MITHRA: Bleeding gums may indicate gum disease. Maintain oral hygiene and see a dentist.",
  "bad breath": "🤖 MITHRA: Brush, floss, and clean your tongue. Persistent bad breath should be checked by a dentist.",
  "oral hygiene": "🤖 MITHRA: Brush twice daily, floss once, and use mouthwash to maintain oral health.",
  "wisdom tooth pain": "🤖 MITHRA: Pain may be due to impaction. Consult a dentist for evaluation and treatment.",
  "braces care": "🤖 MITHRA: Brush after every meal, avoid sticky foods, and visit your orthodontist regularly.",
  "teeth whitening": "🤖 MITHRA: Use dentist-recommended products and avoid harsh chemicals on teeth.",
  "sensitive teeth": "🤖 MITHRA: Use a desensitizing toothpaste and avoid extremely hot or cold foods.",
  "oral infections": "🤖 MITHRA: Rinse with antiseptic solutions and see a dentist for proper treatment.",

  // Skin & Hair Care
  "acne": "🤖 MITHRA: Wash your face gently, avoid touching pimples, and use dermatologist-recommended products.",
  "dry skin": "🤖 MITHRA: Moisturize daily and drink plenty of water.",
  "oily skin": "🤖 MITHRA: Cleanse gently twice a day and avoid heavy creams.",
  "hair fall": "🤖 MITHRA: Eat a balanced diet, avoid stress, and use mild shampoos.",
  "dandruff": "🤖 MITHRA: Use anti-dandruff shampoos and maintain scalp hygiene.",
  "eczema": "🤖 MITHRA: Moisturize, avoid triggers, and consult a dermatologist.",
  "psoriasis": "🤖 MITHRA: Use medicated creams, avoid stress, and consult a dermatologist.",
  "sunburn": "🤖 MITHRA: Apply aloe vera, stay hydrated, and avoid sun exposure until healed.",
  "skin rash": "🤖 MITHRA: Avoid irritants, apply soothing creams, and seek medical advice if severe.",
  "hair care": "🤖 MITHRA: Wash hair regularly, avoid excessive heat, and use natural oils for nourishment.",

  // Yoga, Meditation, Fitness
  "yoga": "🤖 MITHRA: Yoga improves flexibility, reduces stress, and enhances overall well-being.",
  "meditation": "🤖 MITHRA: Meditate daily for mental clarity and stress reduction.",
  "pilates": "🤖 MITHRA: Pilates strengthens core muscles and improves posture.",
  "cardio exercise": "🤖 MITHRA: Cardio activities like running or cycling improve heart health.",
  "strength training": "🤖 MITHRA: Use weights or body resistance to build muscle and bone strength.",
  "stretching": "🤖 MITHRA: Stretching before and after exercise prevents injuries and improves flexibility.",
  "breathing exercises": "🤖 MITHRA: Practice deep breathing to reduce stress and increase lung capacity.",
  "morning workout": "🤖 MITHRA: Morning workouts boost energy and metabolism.",
  "evening workout": "🤖 MITHRA: Evening workouts help relieve stress and improve sleep quality.",
  "home exercises": "🤖 MITHRA: Simple bodyweight exercises like squats, pushups, and planks maintain fitness at home.",

  // Nutrition by Food Groups
  "fruits": "🤖 MITHRA: Eat a variety of fruits daily for vitamins, minerals, and antioxidants.",
  "vegetables": "🤖 MITHRA: Include leafy greens and colorful vegetables for essential nutrients.",
  "protein": "🤖 MITHRA: Consume lean meats, beans, and legumes for muscle repair and growth.",
  "carbohydrates": "🤖 MITHRA: Include whole grains for energy and fiber.",
  "fats": "🤖 MITHRA: Choose healthy fats from nuts, seeds, and olive oil.",
  "vitamins": "🤖 MITHRA: Vitamins support immune system, skin health, and energy production.",
  "minerals": "🤖 MITHRA: Minerals like calcium and iron are essential for bones and blood health.",
  "hydration tips": "🤖 MITHRA: Drink at least 8 glasses of water daily to stay hydrated.",
  "balanced diet": "🤖 MITHRA: Combine carbohydrates, protein, healthy fats, and fiber for optimal health.",
  "snacking": "🤖 MITHRA: Choose healthy snacks like fruits, nuts, or yogurt instead of sugary foods.",

  // Infant & Child Care
  "baby feeding": "🤖 MITHRA: Breastfeed exclusively for 6 months, then introduce solid foods gradually.",
  "child vaccinations": "🤖 MITHRA: Follow the recommended vaccination schedule for immunity.",
  "child nutrition": "🤖 MITHRA: Provide balanced meals with protein, vitamins, and minerals.",
  "child sleep": "🤖 MITHRA: Children need 9–12 hours of sleep depending on age.",
  "child exercise": "🤖 MITHRA: Encourage active play and outdoor activities daily.",
  "teething": "🤖 MITHRA: Soothe gums with teething rings and consult a pediatrician if needed.",
  "child fever": "🤖 MITHRA: Monitor temperature, keep hydrated, and consult a doctor if high.",
  "child allergies": "🤖 MITHRA: Identify triggers, avoid allergens, and seek medical advice.",
  "child hygiene": "🤖 MITHRA: Teach handwashing, dental care, and personal cleanliness.",
  "child mental health": "🤖 MITHRA: Provide attention, listen, and encourage social interaction.",

  // Geriatric (Elderly) Care
  "arthritis": "🤖 MITHRA: Exercise gently, maintain weight, and follow medication as prescribed.",
  "osteoporosis": "🤖 MITHRA: Consume calcium and vitamin D, and perform weight-bearing exercises.",
  "dementia": "🤖 MITHRA: Keep mentally active, socialize, and consult a doctor for memory issues.",
  "elderly nutrition": "🤖 MITHRA: Include protein, fiber, and micronutrients to maintain strength.",
  "elderly hydration": "🤖 MITHRA: Drink water regularly; dehydration can cause confusion.",
  "fall prevention": "🤖 MITHRA: Ensure safe home environment, remove obstacles, and use support devices.",
  "elderly exercise": "🤖 MITHRA: Low-impact exercises like walking, swimming, or yoga improve mobility.",
  "hearing care": "🤖 MITHRA: Check hearing regularly and use hearing aids if needed.",
  "vision care": "🤖 MITHRA: Regular eye checkups and proper lighting reduce eye strain.",
  "sleep in elderly": "🤖 MITHRA: Maintain a consistent sleep schedule and avoid stimulants before bedtime.",

  // Mental Health Therapies
  "anxiety": "🤖 MITHRA: Practice deep breathing, mindfulness, and consult a mental health professional.",
  "depression": "🤖 MITHRA: Engage socially, exercise, and seek professional counseling.",
  "stress management": "🤖 MITHRA: Use relaxation techniques, time management, and therapy if needed.",
  "cognitive behavioral therapy": "🤖 MITHRA: CBT helps identify negative thought patterns and develop coping strategies.",
  "mindfulness meditation": "🤖 MITHRA: Focus on the present moment to reduce anxiety and improve well-being.",
  "sleep hygiene": "🤖 MITHRA: Maintain regular sleep routine, limit screen time, and create a calm environment.",
  "anger management": "🤖 MITHRA: Practice relaxation, cognitive reframing, and counseling when necessary.",
  "social isolation": "🤖 MITHRA: Connect with friends, family, or community programs for emotional support.",
  "self care": "🤖 MITHRA: Engage in hobbies, exercise, rest, and maintain personal boundaries.",
  "emotional resilience": "🤖 MITHRA: Develop coping skills, social support, and positive thinking.",

  // First Aid & Emergency Basics
  "burn": "🤖 MITHRA: Cool the burn with running water, cover with a clean cloth, and seek medical care if severe.",
  "cut": "🤖 MITHRA: Clean with water, apply antiseptic, and bandage. Seek help if deep.",
  "choking": "🤖 MITHRA: Perform the Heimlich maneuver and call emergency services if needed.",
  "nosebleed": "🤖 MITHRA: Sit upright, pinch nose, and lean forward. Seek medical help if persistent.",
  "fracture": "🤖 MITHRA: Immobilize, apply ice, and get medical attention.",
  "poisoning emergency": "🤖 MITHRA: Call local poison control and follow instructions immediately.",
  "shock": "🤖 MITHRA: Lay the person down, keep warm, and seek emergency help.",
  "allergic reaction": "🤖 MITHRA: Use antihistamines or epinephrine if prescribed and call emergency services for severe reactions.",
  "stroke": "🤖 MITHRA: Call emergency services immediately if sudden weakness, slurred speech, or facial droop occurs.",
  "heart attack": "🤖 MITHRA: Call emergency services, keep calm, and chew aspirin if recommended.",

  // Medical Tests & Diagnostics
  "blood test": "🤖 MITHRA: Blood tests can detect infections, anemia, and organ function.",
  "urine test": "🤖 MITHRA: Checks kidney function, infections, and metabolic disorders.",
  "x-ray": "🤖 MITHRA: Imaging to assess bones, chest, or other internal structures.",
  "mri": "🤖 MITHRA: MRI scans provide detailed images of organs and tissues.",
  "ct scan": "🤖 MITHRA: CT scans detect abnormalities in internal organs.",
  "blood sugar test": "🤖 MITHRA: Monitor glucose levels to manage diabetes.",
  "cholesterol test": "🤖 MITHRA: Measures lipid profile to assess heart disease risk.",
  "pregnancy test": "🤖 MITHRA: Detects pregnancy through hormone levels.",
  "allergy test": "🤖 MITHRA: Determines allergic reactions to substances.",
  "covid test": "🤖 MITHRA: PCR or rapid antigen tests confirm COVID-19 infection."
  
};

// AI fallback using Hugging Face free API
async function getAIAnswer(question) {
  try {
    const response = await fetch("https://api-inference.huggingface.co/models/gpt2", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ inputs: `You are MITHRA, a helpful health assistant. Answer the question: ${question}` })
    });
    const data = await response.json();
    if (data && data[0]?.generated_text) return data[0].generated_text;
    return "🤖 MITHRA: Sorry, I couldn't generate an answer.";
  } catch (error) {
    return "🤖 MITHRA: AI server error, please try again later.";
  }
}

// Combined answer: offline first, AI fallback
async function getAnswer(question) {
  question = question.toLowerCase();
  for (let key in healthFAQ) {
    if (question.includes(key)) return healthFAQ[key];
  }
  return await getAIAnswer(question);
}

// Send message
async function sendMessage() {
  const input = document.getElementById("user-input");
  const userText = input.value.trim();
  if (!userText) return;

  // Display user message
  const userMsg = document.createElement("div");
  userMsg.className = "message user";
  userMsg.innerText = userText;
  chatWindow.appendChild(userMsg);

  // Typing indicator
  const botMsg = document.createElement("div");
  botMsg.className = "message bot";
  botMsg.innerText = "🤖 MITHRA: typing...";
  chatWindow.appendChild(botMsg);
  chatWindow.scrollTop = chatWindow.scrollHeight;

  // Get answer
  const answer = await getAnswer(userText);
  botMsg.innerText = answer;
  chatWindow.scrollTop = chatWindow.scrollHeight;

  input.value = "";
}

// Enter key triggers send
document.getElementById("user-input").addEventListener("keypress", function(e){
  if(e.key === "Enter") sendMessage();
});


